# Generated by Django 5.0.2 on 2024-03-02 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0002_alter_category_parent"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="slug",
            field=models.SlugField(null=True, unique=True),
        ),
    ]
